insert into Category (id, type, capacity, type_car)
values  (1, 'P', 'Medium', 'Public'),
        (2, 'M', 'Low', 'Public'),
        (3, 'P', 'Full', 'Public'),
        (4, 'P', 'Full', 'Private'),
        (5, 'M', 'Full', 'Both'),
        (6, 'P', 'Full', 'Both'),
        (7, 'P', 'Medium', 'Both'),
        (8, 'A', 'Low', 'Private'),
        (9, 'P', 'Low', 'Public'),
        (10, 'A', 'Medium', 'Both'),
        (11, 'M', 'Full', 'Both'),
        (12, 'P', 'Low', 'Private'),
        (13, 'M', 'Full', 'Both'),
        (14, 'A', 'Full', 'Both'),
        (15, 'M', 'Medium', 'Both'),
        (16, 'M', 'Low', 'Private'),
        (17, 'A', 'Low', 'Both'),
        (18, 'A', 'Full', 'Both'),
        (19, 'A', 'Medium', 'Private'),
        (20, 'P', 'Low', 'Public'),
        (21, 'P', 'Medium', 'Both'),
        (22, 'M', 'Full', 'Public'),
        (23, 'M', 'Medium', 'Both'),
        (24, 'P', 'Full', 'Public'),
        (25, 'M', 'Low', 'Private'),
        (26, 'A', 'Medium', 'Private'),
        (27, 'M', 'Full', 'Both');