insert into Vehicle (id, model, type, available)
values  (1, 'aut', 'Moen-Goldner', 0),
        (2, 'non', 'Sawayn Ltd', 1),
        (3, 'laboriosam', 'Jacobs-Kohler', 1),
        (4, 'in', 'Will-Lang', 0),
        (5, 'esse', 'Howell, O''Keefe and Schaefer', 1),
        (6, 'atque', 'Predovic, Littel and Gislason', 1),
        (7, 'est', 'Crooks Ltd', 0),
        (8, 'sit', 'Hayes, Tillman and Kertzmann', 0),
        (9, 'error', 'Wunsch-Prosacco', 1),
        (10, 'eaque', 'Senger-Cormier', 1),
        (11, 'voluptates', 'Collins Ltd', 1),
        (12, 'voluptates', 'Metz-Kozey', 0),
        (13, 'officiis', 'Senger, Dach and Shields', 1),
        (14, 'eveniet', 'Breitenberg-Mraz', 1),
        (15, 'ut', 'Boyer Ltd', 1),
        (16, 'exercitationem', 'Morissette Group', 1),
        (17, 'corporis', 'Spencer, Jenkins and Brakus', 1),
        (18, 'sit', 'Lemke-Dicki', 0),
        (19, 'totam', 'Keeling and Sons', 0),
        (20, 'ullam', 'McCullough, Skiles and Osinski', 0),
        (21, 'qui', 'Herman Ltd', 0),
        (22, 'nihil', 'Volkman, Osinski and Altenwerth', 0),
        (23, 'vel', 'Reinger-Waelchi', 0),
        (24, 'dicta', 'McCullough, Fritsch and Keebler', 1),
        (25, 'qui', 'Leannon Group', 1),
        (26, 'necessitatibus', 'Abshire, Veum and Barrows', 1),
        (27, 'dolorem', 'Hartmann, Reinger and Gottlieb', 1),
        (28, 'minus', 'Connelly, Schimmel and Harris', 1),
        (29, 'rerum', 'Thiel, Kihn and Schuppe', 0),
        (30, 'et', 'Predovic-Prosacco', 1),
        (31, 'impedit', 'Kerluke, Bahringer and Nicolas', 1),
        (32, 'hic', 'Hessel-Bode', 0),
        (33, 'amet', 'Rohan-Gleichner', 0),
        (34, 'adipisci', 'Simonis PLC', 1),
        (35, 'explicabo', 'Satterfield, Flatley and Corkery', 0),
        (36, 'aut', 'Crist, Langworth and Rogahn', 0),
        (37, 'architecto', 'Mueller-Wisoky', 1),
        (38, 'cupiditate', 'Wintheiser-Hessel', 1),
        (39, 'est', 'Klocko-Swift', 1),
        (40, 'modi', 'Smitham-Fay', 1),
        (41, 'nihil', 'Kreiger LLC', 1),
        (42, 'aut', 'DuBuque-Huels', 1),
        (43, 'deleniti', 'Abbott, Prohaska and Kilback', 0),
        (44, 'delectus', 'Runte, Hills and Dare', 1),
        (45, 'architecto', 'Hodkiewicz Inc', 0),
        (46, 'illum', 'Becker, Donnelly and Runte', 1),
        (47, 'vitae', 'Mills Ltd', 0),
        (48, 'sed', 'Bogan, McGlynn and Luettgen', 0),
        (49, 'nostrum', 'Bergnaum and Sons', 1),
        (50, 'porro', 'Daniel, Rempel and Borer', 1);